# Generated by Django 4.0.1 on 2022-01-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('third_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('characteristic', models.CharField(max_length=250, verbose_name='Характеристика')),
                ('addres', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=100, verbose_name='Оклад')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.employees')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='positions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.positions'),
        ),
        migrations.CreateModel(
            name='EmployeeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=50, verbose_name='Количество отработанных дней')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.employees')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.projects')),
            ],
        ),
    ]
